### ISSUE TITLE
In-house solution

### ISSUE THREAD

**Issue by dikaso** [kurdin/console-remote#10]
I sent you email but no response so lets try it here :)
Is it possible to host it in-house?

**Comment by kurdin** [comment]
@dikaso sorry, I did not see your email. I'll be open sourcing everything soon if you still interesting.

**Comment by dikaso** [comment]
Great. I am still interested.

**Comment by kurdin** [comment]
@dikaso 👍

**Comment by kurdin** [comment]
@dikaso 
Console Remote Server is available here: https://github.com/kurdin/console-remote-server
