### ISSUE TITLE
Using the HTML <script> tag with private server yields a warning and no logs

### ISSUE THREAD

**Issue by elpollodiablo** [kurdin/console-remote#12]
I included

     <script src="https://tty.my.domain/connector.js" data-channel="100f-8a9b-b669" data-server="https://tty.my.domain" id="consolere"></script>

as per the documentation, but get the warning

    connector.js:2 consoleRe [warning] seems like you trying to use console remote on public, production server. Console.Re is for light, local development only, for production you can install and use self hosted solution https://console.re/#self-hosted-server

**Comment by elpollodiablo** [comment]
Sometimes (this might be a race condition) there is a debugger console log entry and console.re can be used in the debugger. But apparently nothing is being sent to the server with the above config.

**Comment by elpollodiablo** [comment]
Apparently, this is not related to the script tag method, but seems to be an issue with the method of detecting non-local use, which automatically assumes that the software isn't self hosted:

    var isLocal = window.location.port
      ? true
      : /localhost|[0-9]{2,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|::1|\.local|local|runjs\.co|\.dev|console.re|^$/gi.test(
          window.location.hostname
        )
      ? true
      : false
      
      // ...
      
        api.connectIO = function (r) {
    if (!isLocal) {
      console.warn(
        'consoleRe [warning] seems like you trying to use console remote on public, production server. Console.Re is for light, local development only, for production you can install and use self hosted solution https://console.re/#self-hosted-server'  
      )
      return
    }

**Comment by elpollodiablo** [comment]
I have resolved this issue by removing

      if (!isLocal) {
        console.warn(
          'consoleRe [warning] seems like you trying to use console remote on public, production server. Console.Re is for light, local development only, for production you can install and use self hosted solution https://console.re/#self-hosted-server'  
        )
        return
      }

and then running

    ./node_modules/.bin/webpack
    cp ./dist/connector.js ../console-remote-server/build/

**Comment by kurdin** [comment]
@elpollodiablo, yeah I should not even check `isLocal` if server name is not `console.re` . I'll update, thanks!

**Comment by kurdin** [comment]
@elpollodiablo can you please install and try updated version @2.1.15

**Comment by elpollodiablo** [comment]
I did, and it works fine, thanky you!
