### ISSUE TITLE
Typescript support ?

### ISSUE THREAD

**Issue by omatrot** [kurdin/console-remote#4]
Any directions to use this api in a typescript project ?
Thanks in advance.

**Comment by skicomdev** [comment]
@omatrot I am not familiar with TypeScript but I guess it can run standard JS methods so if you add consolere init script on your page like this:

``<script src="//console.re/connector.js" data-channel="my-website-channel" id="consolerescript"></script>``

you can use ``console.re[method]`` in your TypeScript code. 

also you can add TypeScript wrapper class for console.re.log something like this:

```js
class RemoteLog implements RemoteLogInterface {
	public log(msg: string, ...supportingDetails: any[]): void {
		this.emitLogMessage("log", msg, supportingDetails);
	}

	public info(msg: string, ...supportingDetails: any[]): void {
		this.emitLogMessage("info", msg, supportingDetails);
	}

	// add more console.re methods here
  
	private emitLogMessage(msgType: any[], msg: string, supportingDetails: any[]) {
		if (supportingDetails.length > 0) {
    	console.re.log(msg, supportingDetails);
    } else { console.re.log(msg); }
	}
}

let logre = new RemoteLog();

logre.info('test');
```

Here is examples: http://jsfiddle.net/t151b723/

**Comment by kurdin** [comment]
@omatrot I am not familiar with TypeScript but I guess it can run standard JS methods so if you add consolere init script on your page like this:

``<script src="//console.re/connector.js" data-channel="my-website-channel" id="consolerescript"></script>``

you can use ``console.re[method]`` in your TypeScript code. 

also you can add TypeScript wrapper class for console.re.log something like this:

```js
class RemoteLog implements RemoteLogInterface {
	public log(msg: string, ...supportingDetails: any[]): void {
		this.emitLogMessage("log", msg, supportingDetails);
	}

	public info(msg: string, ...supportingDetails: any[]): void {
		this.emitLogMessage("info", msg, supportingDetails);
	}

	// add more console.re methods here
  
	private emitLogMessage(msgType: any[], msg: string, supportingDetails: any[]) {
		if (supportingDetails.length > 0) {
    	console.re.log(msg, supportingDetails);
    } else { console.re.log(msg); }
	}
}

let logre = new RemoteLog();

logre.info('test');
```

Here is examples: http://jsfiddle.net/t151b723/
