### ISSUE TITLE
Consolere prevent NodeJS to gracefully exit

### ISSUE THREAD

**Issue by JosselinTD** [kurdin/console-remote#5]
Hi !
I wanted to use console.re to help me debugging from an AWS Lambda function.

It work as intended and allow me to access logs in realtime which is awesome (AWS Lambda is a real pain on this), but once console.re is connected, the Lambda function never stop until timeout.

I reproduce it locally with this simple script :
```
var consolere = require('console-remote-client').connect('console.re','80','debugging-consolere');

console.re.log('yo');
```

Once started, this script never end.
It seems to be due to Node waiting to all connection to be closed before ending. So, to allow Node JS to end, consolere should have a "disconnect" or "close" function. Is there a way to do this on the current version ?

Thanks a lot !

**Comment by kurdin** [comment]
@JosselinTD  I'll and let you know.

**Comment by kurdin** [comment]
@JosselinTD try this

```js
var consolere = require('console-remote-client').connect('console.re','80','debugging-consolere', true);
console.re.log('yo');
```

**Comment by JosselinTD** [comment]
It work well with one log, but not for a more complex script. It stop the connection after just one log.

**Comment by kurdin** [comment]
@JosselinTD I added api.disconnect to node.connector.js but its not working for me well. I'll keep it there for now. You can try new version from npm.

**Comment by kurdin** [comment]
@JosselinTD if you wrap disconnect with setTimeout the end of the script, everything seems to be working as expected.

`setTimeout(function(){ console.re.disconnect() }, 1000);`
