### ISSUE TITLE
Error logging objects

### ISSUE THREAD

**Issue by karneaud** [kurdin/console-remote#7]
I'm using the following to log javascript objects in ES6 

`console.re.log(ev);`

However I am getting the following

> Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
> at getStyle (connector.js:3)
>     at getSize (connector.js:3)

Looking at the code I see

```
    function getStyle(t, e) {
        return t && t.currentStyle ? t.currentStyle[e] : window.getComputedStyle ? document.defaultView.getComputedStyle(t, null).getPropertyValue(e) : ""
    }
```

**Comment by kurdin** [comment]
@karneaud in what browser do you use this error ?

**Comment by karneaud** [comment]
@kurdin macOS Safari

**Comment by kurdin** [comment]
@karneaud I just tried in Safari, no errors. May be you have older Safari version? I use 11

Can you try to reproduce it here: http://tryes6.com/F7ToESczs and share link with me.

**Comment by karneaud** [comment]
@kurdin sorry was unable to reproduce the error. I believe it may have been an internal error on my side
